
pipe4: pipe4.c ./headers/find_value.h ./headers/pipe_fork.h ./headers/get_up.h
	gcc -Wall pipe4.c -o pipe4

fetch_info: fetch_info.c ./headers/find_value.h ./headers/get_up.h ./headers/pipe_fork.h
	gcc -Wall fetch_info.c -o fetch_info 


